# Generated by Django 4.2.5 on 2023-09-25 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriatest')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_respuesta', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=14, null=True, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=140, null=True, verbose_name='Correo Electronico')),
                ('first_name', models.CharField(max_length=40, null=True, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=150, null=True, verbose_name='Apellidos')),
                ('password1', models.CharField(max_length=15, null=True, verbose_name='Contraseña')),
                ('password2', models.CharField(max_length=15, null=True, verbose_name='Confirmar Contraseña')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuarios',
                'db_table': 'Usuarios',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
