# Generated by Django 4.2.5 on 2023-09-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_resultado_resultadopregunta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriatest',
            options={'ordering': ['id'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterField(
            model_name='categoriatest',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='categoriatest',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterModelTable(
            name='categoriatest',
            table='category',
        ),
    ]
