# Generated by Django 4.2.5 on 2023-09-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_categoriatest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriatest',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
