# Generated by Django 4.2.5 on 2023-09-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_categoriatest_slug_resultado_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='puntuacion_max',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='resultado',
            name='puntuacion_min',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
