# Generated by Django 4.2.7 on 2023-12-10 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'category',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(choices=[('Cedula de ciudadania', 'C.C'), ('tarjeta de identidad', 'T.I'), ('Cedula de extranjeria', 'C.T'), ('Permiso Especial de Permanencia', 'P.P'), ('Permiso por proteccion temporal', 'P.T')], max_length=31)),
                ('nombre', models.CharField(max_length=255)),
                ('nacido', models.IntegerField()),
                ('hm', models.CharField(max_length=1)),
                ('edad', models.CharField(max_length=10)),
                ('nombre_acompanante', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_acompanante', models.CharField(blank=True, choices=[('tutor', 'Tutor'), ('representante', 'Representante')], max_length=20, null=True)),
                ('documento_acompanante', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
                ('jornada', models.CharField(choices=[('mañana', 'Jornada de la Mañana (6 AM - 12 PM)'), ('tarde', 'Jornada de la Tarde (1 PM - 6 PM)'), ('noche', 'Jornada de la Noche (7 PM - 10 PM)'), ('madrugada', 'Jornada de la Madrugada (10 PM - 6 AM)'), ('finesdesemana', 'Jornada de Fines de semana (8 AM - 5 PM)')], max_length=20)),
                ('psicologo', models.CharField(choices=[('Maria Camila Vega', 'Maria Camila Vega'), ('Rosa Telma Cortes', 'Rosa Telma Cortes'), ('Daniela Ortiz', 'Daniela Ortiz'), ('Magerli Flores', 'Magerli Flores')], max_length=100)),
                ('fecha_encuentro', models.DateField()),
                ('razon', models.TextField()),
                ('acepta_terminos', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Encuentros',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('color', models.CharField(max_length=20)),
                ('editable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriatest')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_respuesta', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('puntuacion_min', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('puntuacion_max', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.respuesta')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resultado')),
            ],
        ),
    ]
