# Generated by Django 5.0 on 2023-12-06 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_respuesta', models.TextField()),
                ('tipo_respuesta', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='eleccionusuario',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='eleccionusuario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='historia',
            name='respuestas',
        ),
        migrations.RemoveField(
            model_name='historia',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='respuestausuario',
            name='historia',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='respuestausuario',
            name='respuesta',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.CreateModel(
            name='DailyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_positive', models.IntegerField(default=0)),
                ('count_neutral', models.IntegerField(default=0)),
                ('count_negative', models.IntegerField(default=0)),
                ('daily_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.dailytest')),
            ],
        ),
        migrations.CreateModel(
            name='DailyTestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.dailytestresult')),
            ],
        ),
        migrations.CreateModel(
            name='DailyTestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dailytest')),
                ('selected_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.question'),
        ),
        migrations.DeleteModel(
            name='CategoriaTest',
        ),
        migrations.DeleteModel(
            name='EleccionUsuario',
        ),
        migrations.DeleteModel(
            name='Historia',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
        migrations.DeleteModel(
            name='RespuestaUsuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
